spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/flyway_db
    username: flyway
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    baseline-version: '0'