version: '3.8'
services:
  soap_producer:
    build:
      dockerfile: Dockerfile
      context: ../soap-producer
    ports:
      - "8080:8080"
  db:
    image: postgres
    ports:
      - "8001:5432"