spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect